### ISSUE TITLE
Too many open files - getcwd (Errno::EMFILE)

### ISSUE THREAD

**Issue by jacquescrocker** [infochimps-labs/configliere#27]
When running `Settings.read('./config.yaml')` I'm getting this:

```
/Users/jc/.rvm/gems/ruby-2.2.1/gems/configliere-0.4.22/lib/configliere/config_file.rb:114:in `expand_path': Too many open files - getcwd (Errno::EMFILE)
	from /Users/jc/.rvm/gems/ruby-2.2.1/gems/configliere-0.4.22/lib/configliere/config_file.rb:114:in `expand_filename'
	from /Users/jc/.rvm/gems/ruby-2.2.1/gems/configliere-0.4.22/lib/configliere/config_file.rb:37:in `read'
```

Still tracing. When I comment out my `Settings.read`, it doesn't error out.

**Comment by jacquescrocker** [comment]
This might be unrelated to configliere
